import os
import pandas as pd
import numpy as np
import random
import threading
from sklearn.ensemble import RandomForestClassifier
import db

# ==========================================================================
# VIVI MACHINE LEARNING PREDICTION BRAIN (20,000+ ROUNDS ESTIMATOR)
# ==========================================================================
class MLBrain:
    def __init__(self):
        self.size_model = None
        self.color_model = None
        self.is_trained = False
        self.features_list = []
        self.lag_window = 8
        self.lock = threading.Lock()
        
    def train_from_excel(self):
        """Loads the historical rounds and trains Random Forest models."""
        with self.lock:
            try:
                if db.use_postgres:
                    print("[MLBrain] Ingesting training dataset directly from PostgreSQL database...")
                    records = db.pg_execute("SELECT period_id, number, size, color FROM rounds ORDER BY period_id ASC;", fetch='all')
                    df = pd.DataFrame(records)
                    if len(df) == 0:
                        print("[MLBrain Warning] No rounds found in PostgreSQL database. Bypassing ML initialization.")
                        return False
                    df['period_id'] = df['period_id'].astype(str).str.strip().str.split('.').str[0]
                    df = df[df['period_id'] != 'nan']
                    df = df.drop_duplicates(subset=['period_id'], keep='last')
                else:
                    base_dir = os.path.dirname(os.path.abspath(__file__))
                    excel_path = os.path.abspath(os.path.join(base_dir, "..", "EXTRACTED", "rounds.xlsx"))
                    if not os.path.exists(excel_path):
                        excel_path = os.path.abspath(os.path.join(base_dir, "..", "rounds.xlsx"))
                    
                    print(f"[MLBrain] Resolving Excel archive pathway at: {excel_path}")
                    if not os.path.exists(excel_path):
                        print("[MLBrain Warning] Excel archive file not found. Bypassing ML initialization.")
                        return False

                    # Ingest data from the Excel sheets
                    df = pd.read_excel(excel_path, dtype={'period_id': str}, engine='openpyxl')
                    if 'period_id' in df.columns:
                        df['period_id'] = df['period_id'].astype(str).str.strip().str.split('.').str[0]
                        df = df[df['period_id'] != 'nan']
                        df = df.drop_duplicates(subset=['period_id'], keep='last')




                
                # Sort from oldest to newest to preserve chronological temporal dependencies
                df = df.sort_values("period_id", ascending=True).reset_index(drop=True)
                
                if len(df) < 100:
                    print(f"[MLBrain Warning] Dataset size ({len(df)}) too small to initialize machine learning.")
                    return False
                
                print(f"[MLBrain] Ingested {len(df)} rounds. Constructing rolling lag vectors...")
                
                # Encode values (Binary representation)
                df['size_encoded'] = df['size'].apply(lambda x: 1 if str(x).strip().lower() == 'big' else 0)
                df['color_encoded'] = df['color'].apply(lambda x: 1 if 'red' in str(x).strip().lower() else 0)
                
                features = []
                lag_window = self.lag_window
                
                # Generate lag features (lags 1 through 8)
                for lag in range(1, lag_window + 1):
                    df[f'num_lag_{lag}'] = df['number'].shift(lag)
                    df[f'size_lag_{lag}'] = df['size_encoded'].shift(lag)
                    df[f'color_lag_{lag}'] = df['color_encoded'].shift(lag)
                    features.extend([f'num_lag_{lag}', f'size_lag_{lag}', f'color_lag_{lag}'])
                
                # Generate rolling statistical window features
                df['rolling_size_5'] = df['size_encoded'].shift(1).rolling(5).mean()
                df['rolling_color_5'] = df['color_encoded'].shift(1).rolling(5).mean()
                df['rolling_size_15'] = df['size_encoded'].shift(1).rolling(15).mean()
                df['rolling_color_15'] = df['color_encoded'].shift(1).rolling(15).mean()
                
                features.extend(['rolling_size_5', 'rolling_color_5', 'rolling_size_15', 'rolling_color_15'])
                
                # Drop NaN rows generated by shift operations
                df_clean = df.dropna().reset_index(drop=True)
                
                if len(df_clean) < 100:
                    print("[MLBrain Error] Dataset cleaned size insufficient after feature engineering.")
                    return False
                
                X = df_clean[features]
                y_size = df_clean['size_encoded']
                y_color = df_clean['color_encoded']
                
                print("[MLBrain] Fitting High-Performance Random Forest Classifiers...")
                
                # Initialize classifiers optimized to prevent overfitting on highly random distributions
                self.size_model = RandomForestClassifier(n_estimators=180, max_depth=6, min_samples_leaf=4, random_state=42, n_jobs=-1)
                self.size_model.fit(X, y_size)
                
                self.color_model = RandomForestClassifier(n_estimators=180, max_depth=6, min_samples_leaf=4, random_state=42, n_jobs=-1)
                self.color_model.fit(X, y_color)
                
                self.features_list = features
                self.is_trained = True
                print(f"[MLBrain Success] Random Forest successfully trained! Optimized on {len(df_clean)} rows.")
                return True
                
            except Exception as e:
                print(f"[MLBrain Error] MLBrain Training Exception: {e}")
                return False

    def predict_next(self, recent_rounds):
        """Predicts the next round outcome based on active recent rolling inputs."""
        if not self.is_trained:
            return None
            
        with self.lock:
            try:
                # Convert list of recent dicts to DataFrame sorted chronologically
                df_recent = pd.DataFrame(recent_rounds)
                df_recent = df_recent.sort_values("period_id", ascending=True).reset_index(drop=True)
                
                if len(df_recent) < 15:
                    return None
                
                # Encode values
                df_recent['size_encoded'] = df_recent['size'].apply(lambda x: 1 if str(x).strip().lower() == 'big' else 0)
                df_recent['color_encoded'] = df_recent['color'].apply(lambda x: 1 if 'red' in str(x).strip().lower() else 0)
                
                # Build predictive lag dictionary
                feat_dict = {}
                lag_window = self.lag_window
                
                for lag in range(1, lag_window + 1):
                    idx = len(df_recent) - lag
                    if idx >= 0:
                        feat_dict[f'num_lag_{lag}'] = float(df_recent.loc[idx, 'number'])
                        feat_dict[f'size_lag_{lag}'] = float(df_recent.loc[idx, 'size_encoded'])
                        feat_dict[f'color_lag_{lag}'] = float(df_recent.loc[idx, 'color_encoded'])
                    else:
                        return None
                
                # Build rolling metrics
                feat_dict['rolling_size_5'] = float(df_recent['size_encoded'].tail(5).mean())
                feat_dict['rolling_color_5'] = float(df_recent['color_encoded'].tail(5).mean())
                feat_dict['rolling_size_15'] = float(df_recent['size_encoded'].tail(15).mean())
                feat_dict['rolling_color_15'] = float(df_recent['color_encoded'].tail(15).mean())
                
                # Convert feature map to 2D vector matching training columns
                X_pred = pd.DataFrame([feat_dict])[self.features_list]
                
                # Extract probabilities
                size_prob = self.size_model.predict_proba(X_pred)[0] # [Prob(0), Prob(1)]
                color_prob = self.color_model.predict_proba(X_pred)[0]
                
                pred_size = "Big" if size_prob[1] >= 0.5 else "Small"
                pred_color = "Red" if color_prob[1] >= 0.5 else "Green"
                
                # Convert probability ratios to readable percentage scores
                size_conf = max(size_prob) * 100.0
                color_conf = max(color_prob) * 100.0
                
                # Inject minor variance to prevent interface flatlining, bounded between 55% and 99.9%
                size_conf = min(99.9, max(55.0, size_conf + random.uniform(-1.0, 1.0)))
                color_conf = min(99.9, max(55.0, color_conf + random.uniform(-1.0, 1.0)))
                
                return {
                    "size": pred_size,
                    "color": pred_color,
                    "size_confidence": round(size_conf, 1),
                    "color_confidence": round(color_conf, 1)
                }
                
            except Exception as e:
                print(f"[MLBrain Warning] MLBrain Prediction Exception: {e}")
                return None

# Global ML instance
ml_brain = MLBrain()

# Trigger async ML model training on thread initialization
def trigger_ml_training():
    threading.Thread(target=ml_brain.train_from_excel, daemon=True).start()

# Launch training instantly
trigger_ml_training()

def generate_forecast():
    """
    Ultimate Bulletproof Forecast Brain: 
    Utilizes state-of-the-art Random Forest classifications with a robust fallback statistical heuristic.
    """
    try:
        # Load the latest rounds from Excel DB
        all_data = db.get_latest_rounds(30)

        
        if not all_data or len(all_data) < 15:
            return {
                "size": "WAIT", 
                "color": "TRAINING", 
                "size_confidence": 45.0,
                "color_confidence": 45.0
            }
            
        # 1. ATTEMPT REAL-TIME ML RANDOM FOREST ESTIMATION
        if ml_brain.is_trained:
            ml_pred = ml_brain.predict_next(all_data)
            if ml_pred:
                return ml_pred
                
        # 2. FOOLPROOF MATHEMATICAL FALLBACK IN CASE ML LOADING DELAYS
        big_t = 0
        small_t = 0
        green_t = 0
        red_t = 0
        
        for r in all_data[:20]:
            sz = str(r.get('size', '')).lower()
            cl = str(r.get('color', '')).lower()
            if sz == 'big': big_t += 1
            if sz == 'small': small_t += 1
            if 'green' in cl: green_t += 1
            if 'red' in cl: red_t += 1
            
        s_ratio = max(big_t, small_t) / max(1, big_t + small_t)
        c_ratio = max(green_t, red_t) / max(1, green_t + red_t)
        
        pred_size = "Big" if big_t > small_t else "Small"
        pred_color = "Red" if red_t > green_t else "Green"
        
        fallback_s = min(95.0, 55.0 + (s_ratio - 0.5) * 60.0 + random.uniform(0, 3.0))
        fallback_c = min(95.0, 55.0 + (c_ratio - 0.5) * 60.0 + random.uniform(0, 3.0))
        
        return {
            "size": pred_size,
            "color": pred_color,
            "size_confidence": round(fallback_s, 1),
            "color_confidence": round(fallback_c, 1)
        }
        
    except Exception as e:
        print(f"Global Brain Error: {e}")
        return {
            "size": "WAIT", 
            "color": "WAIT", 
            "size_confidence": 0.0, 
            "color_confidence": 0.0
        }
