import os
import time
import requests
import threading
import traceback
import json
from datetime import datetime, timezone
from db import db_mgr, execute_one

# Constants
WINGO_URL = "https://draw.ar-lottery01.com/WinGo/WinGo_30S/GetHistoryIssuePage.json"
INTERVAL = 5  # Poll every 5 seconds

def get_color(number):
    num = int(number)
    if num == 0: return "RedViolet"
    if num == 5: return "GreenViolet"
    if num in [1, 3, 7, 9]: return "Green"
    return "Red"

def get_size(number):
    return "Big" if int(number) >= 5 else "Small"

def fetch_data():
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        "Accept": "application/json",
        "Referer": "https://draw.ar-lottery01.com/"
    }
    # Add dummy cache buster timestamp
    ts = int(time.time() * 1000)
    url = f"{WINGO_URL}?ts={ts}"
    
    try:
        response = requests.get(url, headers=headers, timeout=10)
        if response.status_code == 200:
            data = response.json()
            # Data is usually in data -> list
            if isinstance(data, dict):
                return data.get("data", {}).get("list", []) or []
            elif isinstance(data, list):
                return data
        return []
    except Exception as e:
        print(f"❌ Miner Network Error: {e}")
        return []

def process_records(records):
    if not records:
        return 0
    
    saved_count = 0
    
    # Process oldest to newest
    for rec in reversed(records):
        try:
            period_id = int(rec.get("issueNumber"))
            num = int(rec.get("number"))
            size = get_size(num)
            color = get_color(num)
            raw = json.dumps(rec)
            
            # Explicit UTC timestamp generated by Python ensures perfect synchronization
            now_utc = datetime.now(timezone.utc)
            
            # Insert into rounds
            conn = db_mgr.get_conn()
            conn.autocommit = True
            cursor = conn.cursor()
            try:
                cursor.execute("""
                    INSERT INTO rounds (period_id, number, size, color, raw_json, created_at)
                    VALUES (%s, %s, %s, %s, %s, %s)
                    ON CONFLICT (period_id) DO NOTHING
                    RETURNING id;
                """, (period_id, num, size, color, raw, now_utc))
                row = cursor.fetchone()
                if row:
                    saved_count += 1
                    # Post-save trigger for updating prediction outcomes if they exist
                    cursor.execute("""
                        UPDATE predictions
                        SET actual_size = %s,
                            actual_color = %s,
                            size_result = CASE WHEN predicted_size = %s THEN 'WIN' ELSE 'LOSS' END,
                            color_result = CASE WHEN POSITION(predicted_color IN %s) > 0 THEN 'WIN' ELSE 'LOSS' END,
                            is_processed = TRUE
                        WHERE period_id = %s AND is_processed = FALSE;
                    """, (size, color, size, color, period_id))
            finally:
                cursor.close()
                db_mgr.release_conn(conn)
                
        except Exception as ex:
            print(f"⚠️ Error inserting record: {ex}")
            continue
            
    return saved_count

def verify_active_prediction():
    """Ensures that if predictions are enabled, the system always holds a forecast for the upcoming period."""
    try:
        active_res = execute_one("SELECT value FROM system_config WHERE key = 'prediction_active'")
        if not active_res or active_res[0] != 'true':
            return
            
        recent = execute_one("SELECT period_id FROM rounds ORDER BY period_id DESC LIMIT 1")
        if not recent:
            return
        latest_id = int(recent[0])
        next_id = latest_id + 1
        
        # Check if database already houses a prediction for this forthcoming block
        exists = execute_one("SELECT 1 FROM predictions WHERE period_id = %s", (next_id,))
        if exists:
            return
            
        import brain
        forecast = brain.generate_forecast()
        if forecast.get("size") == "WAIT":
            return
            
        execute_one("""
            INSERT INTO predictions (period_id, predicted_size, predicted_color, size_confidence, color_confidence, created_at)
            VALUES (%s, %s, %s, %s, %s, CURRENT_TIMESTAMP)
            ON CONFLICT (period_id) DO NOTHING;
        """, (next_id, forecast.get("size"), forecast.get("color"), forecast.get("size_confidence"), forecast.get("color_confidence")))
        print(f"🔮 Daemon Prediction successfully registered for forthcoming Period {next_id}.")
    except Exception as e:
        print(f"⚠️ Autonomous prediction failure: {e}")

def start_miner_loop():
    print("🚀 Initializing Vivi 24/7 Miner...")
    db_mgr.connect()
    
    last_logged = 0
    
    while True:
        try:
            records = fetch_data()
            inserted = process_records(records)
            
            if inserted > 0:
                print(f"📦 Data Ingested: Added {inserted} new rounds from source.")
            
            # Ignite automatic prediction engine verification
            verify_active_prediction()
                
            time.sleep(INTERVAL)
            
        except KeyboardInterrupt:
            print("Stopping miner gracefully...")
            break
        except Exception as e:
            print(f"🔥 FATAL MINER LOOP EXCEPTION:")
            traceback.print_exc()
            time.sleep(10) # Wait longer before retrying after critical crash

def run_in_background():
    miner_thread = threading.Thread(target=start_miner_loop, daemon=True)
    miner_thread.start()
    print("⚡ Miner detached to background thread.")
