-- DATABASE SCHEMA FOR VIVI ENGINE

-- Table to store every historical round fetched from the API
CREATE TABLE IF NOT EXISTS rounds (
    id SERIAL PRIMARY KEY,
    period_id BIGINT UNIQUE NOT NULL,
    number INT NOT NULL,
    size VARCHAR(10) NOT NULL, -- "Big" or "Small"
    color VARCHAR(20) NOT NULL, -- "Red", "Green", "Violet", or "RedViolet", etc.
    raw_json TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Index for faster filtering by creation date/time
CREATE INDEX IF NOT EXISTS idx_rounds_period ON rounds(period_id DESC);
CREATE INDEX IF NOT EXISTS idx_rounds_created ON rounds(created_at DESC);

-- Table for tracking system state (e.g. if prediction mode is running)
CREATE TABLE IF NOT EXISTS system_config (
    key VARCHAR(50) PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO system_config (key, value) 
VALUES ('prediction_active', 'false')
ON CONFLICT (key) DO NOTHING;

-- Table for dual-pipeline prediction analytics
CREATE TABLE IF NOT EXISTS predictions (
    id SERIAL PRIMARY KEY,
    period_id BIGINT UNIQUE NOT NULL,
    
    -- Prediction values generated by brain
    predicted_size VARCHAR(10),
    predicted_color VARCHAR(20),
    confidence FLOAT,
    
    -- Reality values (populated after round concludes)
    actual_size VARCHAR(10),
    actual_color VARCHAR(20),
    
    -- Automatic separated Win/Loss columns
    size_result VARCHAR(10),  -- "WIN" or "LOSS"
    color_result VARCHAR(10), -- "WIN" or "LOSS"
    
    is_processed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_preds_period ON predictions(period_id DESC);
